### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [martabitbrain/directus-extension-sane-image-size#1]
Would like to know which licence this project has, in order to use it for our product.

**Comment by martabitbrain** [comment]
Hi Nils!

I've just added the MIT License to the latest release https://github.com/martabitbrain/directus-extension-sane-image-size/releases/tag/v1.1.1

Cheers.

**Comment by NilsBaumgartner1994** [comment]
Thanks. My own implementation was bound to collections but I like this one more.

**Comment by martabitbrain** [comment]
Feel free to make a pull request if you add per collection configuration or anything that you consider useful :)

**Comment by NilsBaumgartner1994** [comment]
Relied on sharp for Directus 9. But i currently like your code. Small and simple.
