### ISSUE TITLE
Add required metadata to publish on the Directus Extensions Marketplace

### ISSUE THREAD

**Issue by robinsonjohn** [martabitbrain/directus-extension-sane-image-size#2]
To publish on the newly added Directus Extensions Marketplace, the `package.json` file must contain the following:

```
{
  "directus:extension": {
    "host": "^10.3.3",
    "type": "hook"
  }
}
```

See: https://docs.directus.io/extensions/marketplace/publishing.html#required-metadata

In addition, your `README.md` installation instructions (step 1) says to clone the repo to the `extensions/hooks`directory, but Directus now requires all extensions to reside in the root `extensions` directory.

Thank you for this fantastic extension!

**Comment by martabitbrain** [comment]
Thanks @robinsonjohn ! I'll do that as soon as possible :)

**Comment by martabitbrain** [comment]
The extension should appear on the marketplace soon :)

**Comment by robinsonjohn** [comment]
@martabitbrain Sounds great, it will make installation much easier, and hopefully boost the visibility of this great extension. 

Thank you
