### ISSUE TITLE
Sane Image Disk Size in Megabyte

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [martabitbrain/directus-extension-sane-image-size#6]
Maybe it would be also good to not only have the pixel size but also the disk/transfer size as a parameter?

**Comment by NilsBaumgartner1994** [comment]
Any ideas to implement this :-) ?

**Comment by martabitbrain** [comment]
I have no time at the moment, so i'll reopen it just in case :)

**Comment by NilsBaumgartner1994** [comment]
@martabitbrain just wanted to thank you for creating this awesome project.

**Comment by martabitbrain** [comment]
Did some investigation, seems that sharp does not implement it. The only way is brute force (trying several settings until achieving the desired target size), so maybe another approach is better for this (like a cron process that can take its time to make it in the background).

https://github.com/lovell/sharp/issues/3219
